### ISSUE TITLE
[Linux] Segmentation fault in Tempest::Widget::resize(int, int)

### ISSUE THREAD

**Issue by MordragT** [Try/OpenGothic#48]
Hey there,
wanted to try youre opengothic implementation on linux with gothic 2 gold steam. I am using the latest opengothic that compiled on linux. By the way great project didnt know this exists.

**Comment by Try** [comment]
Hi, @MordragT and thanks for reporting!

Unfortunately at this moment Linux machine is out of reach for me due current circumstances, so I need a bit of help to sort this out.

Do you have a `crash.log`(created automatically) file or call-stack?
Do you have same crash on latest(0d570b3) release as well?

**Comment by MordragT** [comment]
I should probably mention that i am not able to start into gothic at all, i see a black window then it exits immediatly. I am getting the crash on the latest release aswell.
I ran the program with valgrind, here is the [log](https://pastebin.com/1V42ezkm).
I dont see a crash.log.

**Comment by Try** [comment]
>I ran the program with valgrind, here is the log.

Thanks, that's worked!
Manage to find NPE in window-probing mechanism and on top of it another memory issue in sounddefinitions.cpp.

The issue should be fixed in 7b94eba

**Comment by MordragT** [comment]
Yes can confirm. Unfortunatly it still crahes on my computer when starting.
Here is the [log](https://pastebin.com/bwGVc97z)

**Comment by Try** [comment]
> Here is the log
Fixed, hopefully now game gonna start :)

**Comment by MordragT** [comment]
I got still one error [log](https://pastebin.com/it9VRDjN) but it seems like the last one

**Comment by Try** [comment]
> I got still one error log but it seems like the last one

That is almost same NPE as in topic, but from other place. It was introduced by my engine update related to better vulkan-device creation.

**Comment by MordragT** [comment]
Ah ok yeah i think there are some more similar bugs. I am at the moment still not able to [launch](https://pastebin.com/xdgkgSrb)

**Comment by Try** [comment]
Last patch wasn't enough - I've made a new one, also tested on a VM

**Comment by MordragT** [comment]
Yes is working now, thanks for fixing it so fast !
